spring.application.name=demo-mvc-alunosenac2026-1

# Configuração de porta para evitar conflito
#server.port=8081

#netstat -ano | findstr :8080
# taskkill /PID <PID_encontrado> /F

#MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/demo_mvc?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=P@ssw0rd

#Thymeleaf
spring.thymeleaf.cache=false